[package]
name = "duct"
version = "1.0.0"
authors = ["oconnor663@gmail.com"]
description = "a library for running child processes"
repository = "https://github.com/oconnor663/duct.rs"
documentation = "https://docs.rs/duct"
readme = "README.md"
license = "MIT"
keywords = ["process", "subprocess", "command", "child", "pipe"]
edition = "2021"

[dependencies]
os_pipe = "1.0.0"
shared_child = { version = "1.1.0", default-features = false }
shared_thread = "0.2.0"

[features]
default = ["timeout"]
timeout = ["shared_child/timeout"]

[target.'cfg(unix)'.dependencies]
libc = "0.2.43"

[dev-dependencies]
tempfile = "3.3.0"
